// src/app/flights/components/utils/sampleResults.js
export const sampleResults = () => [
  {
    id: 1,
    airline: "대한항공",
    flightNo: "KE123",
    departAirport: "ICN (인천)",
    arriveAirport: "NRT (도쿄 나리타)",
    departTime: "09:30",
    arriveTime: "11:45",
    duration: "2시간 15분",
    airlineLogo: "/default-airline.png",
    price: 420000,
    seats: [
      { type: "일반석", price: 420000 },
      { type: "프리미엄", price: 580000 },
      { type: "비즈니스", price: 970000 },
    ],
  },
  {
    id: 2,
    airline: "아시아나항공",
    flightNo: "OZ742",
    departAirport: "ICN (인천)",
    arriveAirport: "KIX (오사카 간사이)",
    departTime: "07:20",
    arriveTime: "09:05",
    duration: "1시간 45분",
    airlineLogo: "/default-airline.png",
    price: 380000,
    seats: [
      { type: "일반석", price: 380000 },
      { type: "프리미엄", price: 520000 },
      { type: "비즈니스", price: 830000 },
    ],
  },
  {
    id: 3,
    airline: "제주항공",
    flightNo: "7C2102",
    departAirport: "ICN (인천)",
    arriveAirport: "CTS (삿포로)",
    departTime: "13:45",
    arriveTime: "16:15",
    duration: "2시간 30분",
    airlineLogo: "/default-airline.png",
    price: 290000,
    seats: [
      { type: "일반석", price: 290000 },
      { type: "프리미엄", price: 370000 },
    ],
  },
  {
    id: 4,
    airline: "ANA (전일본공수)",
    flightNo: "NH866",
    departAirport: "GMP (김포)",
    arriveAirport: "HND (도쿄 하네다)",
    departTime: "14:10",
    arriveTime: "16:35",
    duration: "2시간 25분",
    airlineLogo: "/default-airline.png",
    price: 510000,
    seats: [
      { type: "일반석", price: 510000 },
      { type: "프리미엄", price: 660000 },
      { type: "비즈니스", price: 920000 },
      { type: "퍼스트 클래스", price: 1250000 },
    ],
  },
  {
    id: 5,
    airline: "진에어",
    flightNo: "LJ203",
    departAirport: "ICN (인천)",
    arriveAirport: "PUS (부산 김해)",
    departTime: "10:00",
    arriveTime: "11:10",
    duration: "1시간 10분",
    airlineLogo: "/default-airline.png",
    price: 95000,
    seats: [
      { type: "일반석", price: 95000 },
      { type: "프리미엄", price: 130000 },
    ],
  },
];
