/**
 * 국가별 랜드마크 이미지 URL을 가져오는 함수
 * @param {string} countryCode - 국가 코드 (예: 'US', 'JP', 'KR')
 * @param {string} countryName - 국가 이름 (한국어, 예: '미국', '일본')
 * @returns {Promise<string|null>} 랜드마크 이미지 URL 또는 null
 */
export async function getLandmarkImage(countryCode, countryName) {
	// 국가별 랜드마크 매핑
	const landmarkMap = {
		US: 'Statue of Liberty New York',
		JP: 'Tokyo Tower',
		KR: 'Gyeongbokgung Palace Seoul',
		CN: 'Great Wall of China',
		GB: 'Big Ben London',
		FR: 'Eiffel Tower Paris',
		IT: 'Colosseum Rome',
		ES: 'Sagrada Familia Barcelona',
		DE: 'Brandenburg Gate Berlin',
		AU: 'Sydney Opera House',
		CA: 'CN Tower Toronto',
		TH: 'Wat Pho Bangkok',
		VN: 'Ha Long Bay',
		SG: 'Marina Bay Sands Singapore',
		MY: 'Petronas Twin Towers Kuala Lumpur',
		ID: 'Borobudur Temple',
		PH: 'Chocolate Hills Bohol',
		IN: 'Taj Mahal Agra',
		BR: 'Christ the Redeemer Rio de Janeiro',
		MX: 'Chichen Itza',
		EG: 'Great Pyramid of Giza',
		GR: 'Acropolis Athens',
		TR: 'Hagia Sophia Istanbul',
		RU: 'Red Square Moscow',
		NL: 'Anne Frank House Amsterdam',
		BE: 'Atomium Brussels',
		CH: 'Matterhorn',
		AT: 'Schönbrunn Palace Vienna',
		PT: 'Belem Tower Lisbon',
		DK: 'Little Mermaid Copenhagen',
		SE: 'Vasa Museum Stockholm',
		NO: 'Viking Ship Museum Oslo',
		FI: 'Helsinki Cathedral',
		PL: 'Wawel Castle Krakow',
		CZ: 'Charles Bridge Prague',
		HU: 'Parliament Building Budapest',
		RO: 'Bran Castle',
		BG: 'Alexander Nevsky Cathedral Sofia',
		HR: 'Dubrovnik Old Town',
		IE: 'Cliffs of Moher',
		IS: 'Blue Lagoon Iceland',
		NZ: 'Milford Sound',
		ZA: 'Table Mountain Cape Town',
		MA: 'Hassan II Mosque Casablanca',
		AE: 'Burj Khalifa Dubai',
		SA: 'Mecca',
		IL: 'Western Wall Jerusalem',
		JO: 'Petra',
		LB: 'Cedars of Lebanon',
		TW: 'Taipei 101',
		HK: 'Victoria Peak Hong Kong',
		MO: 'Ruins of St. Paul Macau',
		MN: 'Gandantegchinlen Monastery Ulaanbaatar',
		KZ: 'Bayterek Tower Astana',
		UZ: 'Registan Samarkand',
		KH: 'Angkor Wat',
		LA: 'That Luang Vientiane',
		MM: 'Shwedagon Pagoda Yangon',
		BD: 'Lalbagh Fort Dhaka',
		PK: 'Badshahi Mosque Lahore',
		LK: 'Sigiriya',
		NP: 'Mount Everest',
		BT: 'Tiger\'s Nest Monastery',
		AF: 'Buddhas of Bamiyan',
		IR: 'Persepolis',
		IQ: 'Babylon',
		SY: 'Palmyra',
		YE: 'Old City of Sana\'a',
		OM: 'Sultan Qaboos Grand Mosque',
		QA: 'Museum of Islamic Art Doha',
		KW: 'Kuwait Towers',
		BH: 'Bahrain Fort',
		CL: 'Easter Island',
		AR: 'Iguazu Falls',
		PE: 'Machu Picchu',
		CO: 'Salt Cathedral of Zipaquira',
		EC: 'Galapagos Islands',
		VE: 'Angel Falls',
		UY: 'Colonia del Sacramento',
		PY: 'Jesuit Missions',
		BO: 'Salar de Uyuni',
		CO: 'Cartagena Old Town',
		PA: 'Panama Canal',
		CR: 'Arenal Volcano',
		NI: 'Leon Cathedral',
		HN: 'Copan Ruins',
		GT: 'Tikal',
		BZ: 'Great Blue Hole',
		JM: 'Dunn\'s River Falls',
		CU: 'Old Havana',
		DO: 'Punta Cana',
		HT: 'Citadelle Laferriere',
		PR: 'El Yunque National Forest',
		TT: 'Maracas Bay',
		BB: 'Harrison\'s Cave',
		GD: 'Grand Anse Beach',
		LC: 'Pitons',
		VC: 'Botanical Gardens',
		AG: 'Nelson\'s Dockyard',
		DM: 'Morne Trois Pitons',
		KN: 'Brimstone Hill Fortress',
		BS: 'Pink Sand Beach',
		TC: 'Grace Bay',
		VG: 'The Baths',
		KY: 'Seven Mile Beach',
		BM: 'Horseshoe Bay',
		FK: 'Stanley',
		GF: 'Devil\'s Island',
		SR: 'Paramaribo',
		GY: 'Kaieteur Falls',
		BR: 'Amazon Rainforest',
		PY: 'Iguazu Falls',
		UY: 'Punta del Este',
		AR: 'Perito Moreno Glacier',
		CL: 'Torres del Paine',
		FJ: 'Mamanuca Islands',
		PG: 'Kokoda Track',
		SB: 'Marovo Lagoon',
		VU: 'Mount Yasur',
		NC: 'Lifou',
		PF: 'Bora Bora',
		WS: 'To Sua Ocean Trench',
		TO: 'Ha\'apai',
		TV: 'Funafuti',
		KI: 'Christmas Island',
		NR: 'Anibare Bay',
		PW: 'Rock Islands',
		FM: 'Nan Madol',
		MH: 'Bikini Atoll',
		MP: 'Saipan',
		GU: 'Tumon Bay',
		AS: 'National Park of American Samoa',
		CK: 'Aitutaki',
		NU: 'Alofi',
		PN: 'Adamstown',
		GS: 'Grytviken',
		SH: 'Jamestown',
		AC: 'Green Mountain',
		TA: 'Edinburgh of the Seven Seas',
		IO: 'Diego Garcia',
		CC: 'Direction Island',
		CX: 'Flying Fish Cove',
		NF: 'Kingston',
		HM: 'Mawson Peak',
		AQ: 'McMurdo Station',
		BV: 'Cape Circoncision',
		TF: 'Port-aux-Français',
		PM: 'Saint-Pierre',
		WF: 'Mata-Utu',
		YT: 'Mamoudzou',
		RE: 'Piton de la Fournaise',
		MQ: 'Mount Pelée',
		GP: 'La Soufrière',
		BL: 'Gustavia',
		MF: 'Marigot',
		SX: 'Philipsburg',
		CW: 'Willemstad',
		AW: 'Eagle Beach',
		BQ: 'Kralendijk',
		AN: 'Oranjestad',
		AI: 'Sandy Ground',
		MS: 'Plymouth',
		VG: 'Road Town',
		VI: 'Charlotte Amalie',
		PR: 'San Juan',
		DO: 'Santo Domingo',
		HT: 'Port-au-Prince',
		CU: 'Havana',
		JM: 'Kingston',
		KY: 'George Town',
		TC: 'Cockburn Town',
		BS: 'Nassau',
		BB: 'Bridgetown',
		GD: 'St. George\'s',
		LC: 'Castries',
		VC: 'Kingstown',
		AG: 'St. John\'s',
		DM: 'Roseau',
		KN: 'Basseterre',
		TT: 'Port of Spain',
		SR: 'Paramaribo',
		GY: 'Georgetown',
		GF: 'Cayenne',
		BR: 'Brasília',
		UY: 'Montevideo',
		PY: 'Asunción',
		AR: 'Buenos Aires',
		CL: 'Santiago',
		PE: 'Lima',
		BO: 'La Paz',
		EC: 'Quito',
		CO: 'Bogotá',
		VE: 'Caracas',
		PA: 'Panama City',
		CR: 'San José',
		NI: 'Managua',
		HN: 'Tegucigalpa',
		SV: 'San Salvador',
		GT: 'Guatemala City',
		BZ: 'Belmopan',
		MX: 'Mexico City',
		CA: 'Ottawa',
		US: 'Washington D.C.',
		GL: 'Nuuk',
		IS: 'Reykjavik',
		FO: 'Tórshavn',
		SJ: 'Longyearbyen',
		NO: 'Oslo',
		SE: 'Stockholm',
		FI: 'Helsinki',
		EE: 'Tallinn',
		LV: 'Riga',
		LT: 'Vilnius',
		PL: 'Warsaw',
		DE: 'Berlin',
		DK: 'Copenhagen',
		NL: 'Amsterdam',
		BE: 'Brussels',
		LU: 'Luxembourg',
		FR: 'Paris',
		CH: 'Bern',
		AT: 'Vienna',
		LI: 'Vaduz',
		MC: 'Monaco',
		AD: 'Andorra la Vella',
		ES: 'Madrid',
		PT: 'Lisbon',
		IT: 'Rome',
		SM: 'San Marino',
		VA: 'Vatican City',
		MT: 'Valletta',
		GR: 'Athens',
		AL: 'Tirana',
		MK: 'Skopje',
		ME: 'Podgorica',
		RS: 'Belgrade',
		BA: 'Sarajevo',
		HR: 'Zagreb',
		SI: 'Ljubljana',
		HU: 'Budapest',
		SK: 'Bratislava',
		CZ: 'Prague',
		RO: 'Bucharest',
		BG: 'Sofia',
		MD: 'Chișinău',
		UA: 'Kyiv',
		BY: 'Minsk',
		RU: 'Moscow',
		GE: 'Tbilisi',
		AM: 'Yerevan',
		AZ: 'Baku',
		KZ: 'Astana',
		UZ: 'Tashkent',
		TM: 'Ashgabat',
		TJ: 'Dushanbe',
		KG: 'Bishkek',
		MN: 'Ulaanbaatar',
		CN: 'Beijing',
		TW: 'Taipei',
		HK: 'Hong Kong',
		MO: 'Macau',
		KP: 'Pyongyang',
		KR: 'Seoul',
		JP: 'Tokyo',
		PH: 'Manila',
		VN: 'Hanoi',
		LA: 'Vientiane',
		KH: 'Phnom Penh',
		TH: 'Bangkok',
		MY: 'Kuala Lumpur',
		SG: 'Singapore',
		BN: 'Bandar Seri Begawan',
		ID: 'Jakarta',
		TL: 'Dili',
		MM: 'Naypyidaw',
		BD: 'Dhaka',
		BT: 'Thimphu',
		NP: 'Kathmandu',
		PK: 'Islamabad',
		AF: 'Kabul',
		IR: 'Tehran',
		IQ: 'Baghdad',
		SY: 'Damascus',
		LB: 'Beirut',
		JO: 'Amman',
		IL: 'Jerusalem',
		PS: 'Ramallah',
		SA: 'Riyadh',
		YE: 'Sana\'a',
		OM: 'Muscat',
		AE: 'Abu Dhabi',
		QA: 'Doha',
		BH: 'Manama',
		KW: 'Kuwait City',
		TR: 'Ankara',
		CY: 'Nicosia',
		EG: 'Cairo',
		LY: 'Tripoli',
		TN: 'Tunis',
		DZ: 'Algiers',
		MA: 'Rabat',
		EH: 'Laayoune',
		MR: 'Nouakchott',
		ML: 'Bamako',
		SN: 'Dakar',
		GM: 'Banjul',
		GW: 'Bissau',
		GN: 'Conakry',
		SL: 'Freetown',
		LR: 'Monrovia',
		CI: 'Yamoussoukro',
		GH: 'Accra',
		TG: 'Lomé',
		BJ: 'Porto-Novo',
		NG: 'Abuja',
		NE: 'Niamey',
		TD: 'N\'Djamena',
		CM: 'Yaoundé',
		CF: 'Bangui',
		CG: 'Brazzaville',
		CD: 'Kinshasa',
		GA: 'Libreville',
		GQ: 'Malabo',
		ST: 'São Tomé',
		AO: 'Luanda',
		ZM: 'Lusaka',
		ZW: 'Harare',
		BW: 'Gaborone',
		NA: 'Windhoek',
		ZA: 'Cape Town',
		LS: 'Maseru',
		SZ: 'Mbabane',
		MW: 'Lilongwe',
		MZ: 'Maputo',
		MG: 'Antananarivo',
		MU: 'Port Louis',
		SC: 'Victoria',
		KM: 'Moroni',
		DJ: 'Djibouti',
		ER: 'Asmara',
		ET: 'Addis Ababa',
		SO: 'Mogadishu',
		KE: 'Nairobi',
		UG: 'Kampala',
		RW: 'Kigali',
		BI: 'Gitega',
		TZ: 'Dodoma',
		SS: 'Juba',
		SD: 'Khartoum',
		EG: 'Cairo',
		LY: 'Tripoli',
		TN: 'Tunis',
		DZ: 'Algiers',
		MA: 'Rabat',
		EH: 'Laayoune',
		MR: 'Nouakchott',
		ML: 'Bamako',
		SN: 'Dakar',
		GM: 'Banjul',
		GW: 'Bissau',
		GN: 'Conakry',
		SL: 'Freetown',
		LR: 'Monrovia',
		CI: 'Yamoussoukro',
		GH: 'Accra',
		TG: 'Lomé',
		BJ: 'Porto-Novo',
		NG: 'Abuja',
		NE: 'Niamey',
		TD: 'N\'Djamena',
		CM: 'Yaoundé',
		CF: 'Bangui',
		CG: 'Brazzaville',
		CD: 'Kinshasa',
		GA: 'Libreville',
		GQ: 'Malabo',
		ST: 'São Tomé',
		AO: 'Luanda',
		ZM: 'Lusaka',
		ZW: 'Harare',
		BW: 'Gaborone',
		NA: 'Windhoek',
		ZA: 'Cape Town',
		LS: 'Maseru',
		SZ: 'Mbabane',
		MW: 'Lilongwe',
		MZ: 'Maputo',
		MG: 'Antananarivo',
		MU: 'Port Louis',
		SC: 'Victoria',
		KM: 'Moroni',
		DJ: 'Djibouti',
		ER: 'Asmara',
		ET: 'Addis Ababa',
		SO: 'Mogadishu',
		KE: 'Nairobi',
		UG: 'Kampala',
		RW: 'Kigali',
		BI: 'Gitega',
		TZ: 'Dodoma',
		SS: 'Juba',
		SD: 'Khartoum'
	};

	// 국가 코드로 랜드마크 찾기
	const landmarkName = landmarkMap[countryCode?.toUpperCase()];
	
	if (!landmarkName) {
		// 국가 코드가 없으면 국가 이름으로 기본 이미지 반환
		return null;
	}

	try {
		// Google Places API를 사용하여 랜드마크 이미지 가져오기
		const GOOGLE_API_KEY = process.env.NEXT_PUBLIC_GOOGLE_API_KEY;
		if (!GOOGLE_API_KEY) {
			console.error('Google API 키가 설정되지 않았습니다.');
			return null;
		}

		// Text Search로 랜드마크 검색
		const searchUrl = 'https://places.googleapis.com/v1/places:searchText';
		const searchBody = JSON.stringify({
			textQuery: landmarkName
		});

		const searchRes = await fetch(searchUrl, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
				'X-Goog-Api-Key': GOOGLE_API_KEY,
				'X-Goog-FieldMask': 'places.photos,places.displayName'
			},
			body: searchBody
		});

		if (!searchRes.ok) {
			console.error('랜드마크 검색 실패');
			return null;
		}

		const searchData = await searchRes.json();

		if (!searchData.places || searchData.places.length === 0) {
			console.log(`[랜드마크 검색 실패] '${landmarkName}'에 대한 검색 결과가 없습니다.`);
			return null;
		}

		const place = searchData.places[0];
		const photoName = place.photos?.[0]?.name;

		if (!photoName) {
			console.log(`[랜드마크 검색 실패] '${place.displayName}' 장소는 찾았지만, 연관된 사진이 없습니다.`);
			return null;
		}

		// 사진 URL 생성
		const photoUrl = `https://places.googleapis.com/v1/${photoName}/media?maxWidthPx=800&key=${GOOGLE_API_KEY}`;
		return photoUrl;
	} catch (error) {
		console.error('랜드마크 이미지 가져오기 오류:', error);
		return null;
	}
}

