export const keywordMap = {
	// 자동차 관련
	car_dealer: '자동차 딜러',
	car_rental: '자동차 렌트',
	car_repair: '자동차 정비',
	car_wash: '세차장',
	electric_vehicle_charging_station: '전기차 충전소',
	gas_station: '주유소',
	parking: '주차장',
	rest_stop: '휴게소',

	// 비즈니스
	corporate_office: '기업 사무실',
	farm: '농장',
	ranch: '목장',

	// 문화
	art_gallery: '미술관',
	art_studio: '아트 스튜디오',
	auditorium: '강당',
	cultural_landmark: '문화 명소',
	historical_place: '역사적 장소',
	monument: '기념물',
	museum: '박물관',
	performing_arts_theater: '공연 예술 극장',
	sculpture: '조각상',

	// 교육
	library: '도서관',
	preschool: '유치원',
	primary_school: '초등학교',
	school: '학교',
	secondary_school: '중고등학교',
	university: '대학교',

	// 엔터테인먼트 및 여가
	adventure_sports_center: '모험 스포츠 센터',
	amphitheatre: '야외 극장',
	amusement_center: '오락센터',
	amusement_park: '놀이공원',
	aquarium: '아쿠아리움',
	banquet_hall: '연회장',
	barbecue_area: '바베큐장',
	botanical_garden: '식물원',
	bowling_alley: '볼링장',
	casino: '카지노',
	childrens_camp: '어린이 캠프',
	comedy_club: '코미디 클럽',
	community_center: '커뮤니티 센터',
	concert_hall: '콘서트홀',
	convention_center: '컨벤션센터',
	cultural_center: '문화센터',
	cycling_park: '자전거 공원',
	dance_hall: '댄스홀',
	dog_park: '반려견 공원',
	event_venue: '행사장',
	ferris_wheel: '관람차',
	garden: '정원',
	hiking_area: '등산 코스',
	historical_landmark: '역사적 명소',
	internet_cafe: '인터넷 카페',
	karaoke: '노래방',
	marina: '마리나',
	movie_rental: '영화 대여점',
	movie_theater: '영화관',
	national_park: '국립공원',
	night_club: '나이트클럽',
	observation_deck: '전망대',
	off_roading_area: '오프로드 구역',
	opera_house: '오페라 하우스',
	park: '공원',
	philharmonic_hall: '필하모니홀',
	picnic_ground: '피크닉 장소',
	planetarium: '천문관',
	plaza: '광장',
	roller_coaster: '롤러코스터',
	skateboard_park: '스케이트공원',
	state_park: '주립공원',
	tourist_attraction: '관광 명소',
	video_arcade: '비디오 아케이드',
	visitor_center: '관광안내소',
	water_park: '워터파크',
	wedding_venue: '웨딩장',
	wildlife_park: '야생동물공원',
	wildlife_refuge: '야생동물보호구역',
	zoo: '동물원',

	// 시설
	public_bath: '공중목욕탕',
	public_bathroom: '공중화장실',
	stable: '마구간',

	// 금융
	accounting: '회계사',
	atm: 'ATM',
	bank: '은행',

	// 식음료
	acai_shop: '아사이 전문점',
	afghani_restaurant: '아프가니스탄 음식점',
	african_restaurant: '아프리카 음식점',
	american_restaurant: '미국 음식점',
	asian_restaurant: '아시아 음식점',
	bagel_shop: '베이글가게',
	bakery: '베이커리',
	bar: '바',
	bar_and_grill: '바 앤 그릴',
	barbecue_restaurant: '바베큐 음식점',
	brazilian_restaurant: '브라질 음식점',
	breakfast_restaurant: '아침식당',
	brunch_restaurant: '브런치식당',
	buffet_restaurant: '뷔페',
	cafe: '카페',
	cafeteria: '카페테리아',
	candy_store: '사탕가게',
	cat_cafe: '고양이카페',
	chinese_restaurant: '중국음식점',
	chocolate_factory: '초콜릿공장',
	chocolate_shop: '초콜릿가게',
	coffee_shop: '커피숍',
	confectionery: '과자점',
	deli: '델리',
	dessert_restaurant: '디저트 음식점',
	dessert_shop: '디저트가게',
	diner: '다이너',
	dog_cafe: '반려견카페',
	donut_shop: '도넛가게',
	fast_food_restaurant: '패스트푸드점',
	fine_dining_restaurant: '고급음식점',
	food_court: '푸드코트',
	french_restaurant: '프랑스 음식점',
	greek_restaurant: '그리스 음식점',
	hamburger_restaurant: '햄버거가게',
	ice_cream_shop: '아이스크림가게',
	indian_restaurant: '인도음식점',
	indonesian_restaurant: '인도네시아음식점',
	italian_restaurant: '이탈리아음식점',
	japanese_restaurant: '일본음식점',
	juice_shop: '주스가게',
	korean_restaurant: '한식당',
	lebanese_restaurant: '레바논음식점',
	meal_delivery: '음식 배달',
	meal_takeaway: '음식 포장',
	mediterranean_restaurant: '지중해음식점',
	mexican_restaurant: '멕시코음식점',
	middle_eastern_restaurant: '중동음식점',
	pizza_restaurant: '피자집',
	pub: '펍',
	ramen_restaurant: '라멘집',
	restaurant: '음식점',
	sandwich_shop: '샌드위치가게',
	seafood_restaurant: '해산물식당',
	spanish_restaurant: '스페인음식점',
	steak_house: '스테이크하우스',
	sushi_restaurant: '스시집',
	tea_house: '차집',
	thai_restaurant: '태국음식점',
	turkish_restaurant: '터키음식점',
	vegan_restaurant: '비건음식점',
	vegetarian_restaurant: '채식음식점',
	vietnamese_restaurant: '베트남음식점',
	wine_bar: '와인바',

	// 지역
	administrative_area_level_1: '행정구역 레벨1',
	administrative_area_level_2: '행정구역 레벨2',
	country: '국가',
	locality: '지역',
	postal_code: '우편번호',
	school_district: '학군',

	// 주소 유형 및 주소 구성요소
	street_address: '상세주소',
	route: '경로명',
	intersection: '교차로',
	political: '정치구역',
	colloquial_area: '관용지역명',
	sublocality: '하위지역',
	neighborhood: '동네',
	premise: '건물',
	subpremise: '건물 하위호',
	plus_code: '플러스코드',
	natural_feature: '자연지형',
	point_of_interest: '요즘 뜨는 장소',
	landmark: '랜드마크',
	parking: '주차장',
	post_box: '사서함',
	postal_town: '우편마을',
	room: '방',
	street_number: '번지',

	// 기타(대표/추가)
	shopping_mall: '쇼핑몰',
	clothing_store: '의류점',
	convenience_store: '편의점',
	department_store: '백화점',
	electronics_store: '전자제품점',
	grocery_or_supermarket: '식료품점/슈퍼마켓',
	hardware_store: '철물점',
	jewelry_store: '보석상',
	pet_store: '펫숍',
	shoe_store: '신발가게',
	book_store: '서점',
	beauty_salon: '미용실',
	hair_care: '헤어케어',
	gym: '헬스장',
	spa: '스파',
	stadium: '경기장',
	sports_complex: '스포츠종합시설',
	embassy: '대사관',
	city_hall: '시청',
	government_office: '행정기관',
	market: '시장',
	zoo: '동물원',
	aquarium: '아쿠아리움',
	bus_station: '버스정류장',
	train_station: '기차역',
	airport: '공항',
	fire_station: '소방서',
	police: '경찰서',
	post_office: '우체국',
	hotel: '호텔',
	guest_house: '게스트하우스',
	church: '교회',
	mosque: '모스크',
	synagogue: '시나고그'
	// 필요시 추가작성
};
